name: whrzats
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  http: ^0.13.2
  badges: ^2.0.1

#  firebase_core: ^1.10.0
#  firebase_analytics: ^8.3.4
#  firebase_auth: ^3.2.0
#  cloud_firestore: ^3.1.0
  #  geolocator: ^6.0.0

  webview_flutter:

  flutter:
    sdk: flutter
  geocoding: ^2.0.1
  geolocator: ^7.7.1


dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/icmap.png
    - assets/images/icsearch.png
    - assets/firelogo.png
    - assets/images/ic_add_image.png
    - assets/images/launcher.png
    - assets/images/imageplaceholder.png
    - assets/images/logocircle.png
    - assets/images/index.jpg
    - assets/images/index1.jpg
    - assets/images/index3.jpg
    - assets/images/index4.jpg
    - assets/images/index5.jpg
    - assets/images/index6.jpg
    - assets/images/ic_add_hotspot.png
    - assets/images/ic_add_active.png
    - assets/images/ic_home_active.png
    - assets/images/ic_chat_active.png
    - assets/images/ic_profile_active.png
    - assets/images/ic_edit.png
    - assets/images/ic_settings.png
    - assets/images/ic_like_profile.png
    - assets/images/ic_new_activity.png






  fonts:
   - family: OpenSans
     fonts:
      - asset: assets/fonts/OpenSans-Bold.ttf
      - asset: assets/fonts/OpenSans-Regular.ttf
      - asset: assets/fonts/OpenSans-SemiBold.ttf
        weight: 700


    #
    #     - family: Trajan Pro
    #       fonts:
    #         - asset: assets/fonts/TrajanPro.ttf
    #         - asset: assets/fonts/TrajanPro_Bold.ttf
    #           weight: 700
    #
    # For details regarding fonts from package dependencies,
    # see https://flutter.dev/custom-fonts/#from-packages
